package com.franjo.github.domain.model


data class Repository(
    val author: String = "",
    val archiveUrl: String = "",
    val archived: Boolean = false,
    val assigneesUrl: String = "",
    val blobsUrl: String = "",
    val branchesUrl: String = "",
    val cloneUrl: String = "",
    val collaboratorsUrl: String = "",
    val commentsUrl: String = "",
    val commitsUrl: String = "",
    val compareUrl: String = "",
    val contentsUrl: String = "",
    val contributorsUrl: String = "",
    val createdAt: String = "",
    val defaultBranch: String = "",
    val deploymentsUrl: String = "",
    val description: String = "",
    val disabled: Boolean = false,
    val downloadsUrl: String = "",
    val eventsUrl: String = "",
    val fork: Boolean = false,
    val forks: Int = 0,
    val forksCount: Int = 0,
    val forksUrl: String = "",
    val fullName: String = "",
    val gitCommitsUrl: String = "",
    val gitRefsUrl: String = "",
    val gitTags_url: String = "",
    val gitUrl: String = "",
    val hasDownloads: Boolean = false,
    val hasIssues: Boolean = false,
    val hasPages: Boolean = false,
    val hasProjects: Boolean = false,
    val hasWiki: Boolean = false,
    val homepage: String = "",
    val hooksUrl: String = "",
    val htmlUrl: String = "",
    val id: Int = 0,
    val issueCommentUrl: String = "",
    val issueEventsUrl: String = "",
    val issuesUrl: String = "",
    val keysUrl: String = "",
    val labelsUrl: String = "",
    val programmingLanguage: String = "",
    val languagesUrl: String = "",
    val mergesUrl: String = "",
    val milestonesUrl: String = "",
    val mirrorUrl: Any? = null,
    val name: String = "",
    val nodeId: String = "",
    val notificationsUrl: String = "",
    val openIssues: Int = 0,
    val ownerHtmlUrl: String,
    val ownerUrl: String,
    val issuesCount: Int = 0,
    val `private`: Boolean = false,
    val pullsUrl: String = "",
    val pushedAt: String = "",
    val releasesUrl: String = "",
    val score: Double = 0.0,
    val size: Int = 0,
    val sshUrl: String = "",
    val starsCount: Int = 0,
    val stargazersUrl: String = "",
    val statusesUrl: String = "",
    val subscribersUrl: String = "",
    val subscriptionUrl: String = "",
    val svnUrl: String = "",
    val tagsUrl: String = "",
    val teamsUrl: String = "",
    val thumbnail: String = "",
    val treesUrl: String = "",
    val updatedAt: String = "",
    val url: String = "",
    val watchers: Int = 0,
    val watcherCount: Int = 0
)



